camp = {
	['path'] = 'Mods/aircraft/F14/Missions/Campaigns/Desert F14 89/',
	['date'] = {
		['year'] = 1989,
		['day'] = 10,
		['month'] = 4,
	},
	['idle_time_min'] = 10800,
	['freq_max'] = 400,
	['dawn'] = 18900,
	['idle_time_max'] = 43200,
	['time'] = 116,
	['weather'] = {
		['zoneNextTemp'] = 34,
		['pHigh'] = 60,
		['pLow'] = 40,
		['zoneNext'] = 'high',
		['zoneTemp'] = 42,
		['refTemp'] = 38,
		['zoneEnd'] = 392125,
		['zoneStart'] = 153848,
		['zone'] = 'high',
	},
	['dusk'] = 65700,
	['freq_min'] = 225,
	['debug'] = true,
	['hotstart'] = false,
	['units'] = 'imperial',
	['flag'] = {
	},
	['player'] = {
		['pack'] = {
			['SEAD'] = {
			},
			['main'] = {
				[1] = {
					['number'] = 4,
					['tot_to'] = 10800,
					['properties'] = {
						['INSAlignmentStored'] = true,
					},
					['skill'] = 'High',
					['firepower'] = 40,
					['livery'] = {
						[1] = 'VF-74 Adversary',
					},
					['base'] = 'Nellis AFB',
					['playable'] = true,
					['type'] = 'F-14B',
					['route'] = {
						[7] = {
							['alt'] = 4572,
							['x'] = -283498.57142856,
							['id'] = 'Target',
							['SEAD_radius'] = 23000,
							['eta'] = 1782.0641955981,
							['y'] = -162609.85714285,
						},
						[1] = {
							['alt'] = 0,
							['x'] = -397971,
							['id'] = 'Taxi',
							['eta'] = 2,
							['y'] = -17639.5,
						},
						[2] = {
							['alt'] = 1563,
							['x'] = -397971,
							['id'] = 'Departure',
							['eta'] = 902,
							['y'] = -17639.5,
						},
						[4] = {
							['alt'] = 5486.4,
							['x'] = -306616.22728798,
							['id'] = 'Nav',
							['eta'] = 1638.2224967564,
							['y'] = -133333.15822007,
						},
						[8] = {
							['alt'] = 4572,
							['x'] = -317008.74792447,
							['id'] = 'Egress',
							['eta'] = 1913.5398712738,
							['y'] = -177038.53731336,
						},
						[9] = {
							['alt'] = 5486.4,
							['x'] = -321149.65459339,
							['id'] = 'Nav',
							['eta'] = 1955.9058944398,
							['y'] = -168885.89185564,
						},
						[5] = {
							['alt'] = 4572,
							['x'] = -300949.52456093,
							['id'] = 'IP',
							['eta'] = 1680.5885199224,
							['y'] = -140509.59300366,
						},
						[10] = {
							['alt'] = 5486.4,
							['x'] = -382363.89378212,
							['id'] = 'Split',
							['eta'] = 2582.1947927201,
							['y'] = -48366.877791534,
						},
						[3] = {
							['alt'] = 5486.4,
							['x'] = -376613.15775978,
							['id'] = 'Join',
							['eta'] = 1114.9037837838,
							['y'] = -44687.532928144,
						},
						[6] = {
							['alt'] = 4572,
							['x'] = -290631.21742998,
							['id'] = 'Attack',
							['SEAD_radius'] = 23000,
							['eta'] = 1740.5885199224,
							['y'] = -153576.92011947,
						},
						[11] = {
							['alt'] = 5486.4,
							['x'] = -397971,
							['id'] = 'Land',
							['eta'] = 2741.872630558,
							['y'] = -17639.5,
						},
					},
					['country'] = 'USA',
					['airdromeId'] = 4,
					['loadout'] = {
						['stores'] = {
							['pylons'] = {
								[6] = {
									['CLSID'] = '{LAU-138 wtip - AIM-9M}',
									['num'] = 10,
								},
								[2] = {
									['CLSID'] = '{MAK79_MK82 4}',
									['num'] = 7,
								},
								[3] = {
									['CLSID'] = '{MAK79_MK82 3L}',
									['num'] = 5,
								},
								[1] = {
									['CLSID'] = '{MAK79_MK82 4}',
									['num'] = 4,
								},
								[4] = {
									['CLSID'] = '{MAK79_MK82 3R}',
									['num'] = 6,
								},
								[5] = {
									['CLSID'] = '{LAU-138 wtip - AIM-9M}',
									['num'] = 1,
								},
							},
							['fuel'] = 7348,
							['flare'] = 60,
							['ammo_type'] = 1,
							['chaff'] = 140,
							['gun'] = 100,
						},
						['description'] = {
							['hCruise'] = 5486.4,
							['night'] = false,
							['capability'] = 5,
							['expend'] = 'All',
							['hAttack'] = 4572,
							['attributes'] = {
								[1] = 'soft',
								[2] = 'hard',
								[4] = 'SA-6',
								[3] = 'armor',
							},
							['task'] = 'CAS',
							['vCruise'] = 215.83333333333,
							['LDSD'] = false,
							['day'] = true,
							['self_escort'] = false,
							['adverseWeather'] = false,
							['vAttack'] = 277.5,
							['firepower'] = 10,
							['range'] = 360000,
							['weaponType'] = 'Bombs',
							['sortie_rate'] = 2,
						},
						['name'] = 'CAS MR, Mk-82*14, AIM-7M*2',
					},
					['callsign'] = 'Enfield71',
					['eta_offset'] = 0,
					['player'] = true,
					['name'] = 'FA 1/2',
					['tot_from'] = 0,
					['target_name'] = '103 EWR Site',
					['target'] = {
						['elements'] = {
							[1] = {
								['name'] = '103 Radar',
							},
							[2] = {
								['name'] = '103 Command Post',
							},
						},
						['groupId'] = 61,
						['class'] = 'vehicle',
						['name'] = '103 EWR Site',
						['y'] = -162609.85714285,
						['x'] = -283498.57142856,
						['attributes'] = {
							[1] = 'soft',
						},
						['dead_last'] = 0,
						['alive'] = 100,
						['priority'] = 3,
						['task'] = 'CAS',
						['firepower'] = {
							['min'] = 20,
							['max'] = 20,
						},
					},
					['task'] = 'CAS',
					['frequency'] = 290.65,
				},
			},
			['escort'] = {
			},
		},
		['side'] = 'blue',
		['group'] = {
			['uncontrolled'] = false,
			['taskSelected'] = true,
			['modulation'] = 0,
			['groupId'] = 100215,
			['tasks'] = {
			},
			['route'] = {
				['points'] = {
					[7] = {
						['alt'] = 4572,
						['briefing_name'] = 'Target',
						['action'] = 'Turning Point',
						['alt_type'] = 'BARO',
						['number'] = 6,
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = false,
						['ETA'] = 1782.0641955981,
						['y'] = -162609.85714285,
						['x'] = -283498.57142856,
						['name'] = 'Target: 294/7NM',
						['ETA_locked'] = true,
						['speed'] = 215.83333333333,
						['formation_template'] = '',
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[1] = {
						['speed_locked'] = true,
						['briefing_name'] = 'Taxi',
						['action'] = 'From Parking Area',
						['alt_type'] = 'RADIO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed'] = 5.138,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
									[1] = {
										['number'] = 1,
										['auto'] = false,
										['id'] = 'WrappedAction',
										['enabled'] = true,
										['params'] = {
											['action'] = {
												['id'] = 'Option',
												['params'] = {
													['value'] = 2,
													['name'] = 1,
												},
											},
										},
									},
								},
							},
						},
						['type'] = 'TakeOffParking',
						['ETA'] = 2,
						['ETA_locked'] = true,
						['y'] = -17639.5,
						['x'] = -397971,
						['name'] = 'Taxi',
						['airdromeId'] = 4,
						['alt'] = 0,
						['number'] = 0,
						['formation_template'] = '',
					},
					[2] = {
						['alt'] = 1763,
						['briefing_name'] = 'Departure',
						['action'] = 'Turning Point',
						['alt_type'] = 'BARO',
						['number'] = 1,
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = false,
						['ETA'] = 902,
						['y'] = -17639.5,
						['x'] = -397971,
						['name'] = 'Departure',
						['ETA_locked'] = true,
						['speed'] = 161.875,
						['formation_template'] = '',
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
									[1] = {
										['number'] = 1,
										['auto'] = false,
										['id'] = 'WrappedAction',
										['enabled'] = true,
										['params'] = {
											['action'] = {
												['id'] = 'Option',
												['params'] = {
													['variantIndex'] = 1,
													['value'] = 393217,
													['name'] = 5,
													['formationIndex'] = 6,
												},
											},
										},
									},
									[2] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'ControlledTask',
										['number'] = 2,
										['params'] = {
											['task'] = {
												['id'] = 'Orbit',
												['params'] = {
													['altitude'] = 1763,
													['pattern'] = 'Circle',
													['speed'] = 143.88888888889,
												},
											},
											['stopCondition'] = {
												['time'] = 902,
											},
										},
									},
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[4] = {
						['alt'] = 5486.4,
						['briefing_name'] = 'Nav',
						['action'] = 'Turning Point',
						['alt_type'] = 'BARO',
						['number'] = 3,
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = false,
						['ETA'] = 1638.2224967564,
						['y'] = -133333.15822007,
						['x'] = -306616.22728798,
						['name'] = 'Nav: 294/61NM',
						['ETA_locked'] = true,
						['speed'] = 215.83333333333,
						['formation_template'] = '',
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[8] = {
						['alt'] = 4572,
						['briefing_name'] = 'Egress',
						['action'] = 'Turning Point',
						['alt_type'] = 'BARO',
						['number'] = 7,
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = false,
						['ETA'] = 1913.5398712738,
						['y'] = -177038.53731336,
						['x'] = -317008.74792447,
						['name'] = 'Egress: 189/20NM',
						['ETA_locked'] = true,
						['speed'] = 215.83333333333,
						['formation_template'] = '',
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[9] = {
						['alt'] = 5486.4,
						['briefing_name'] = 'Nav',
						['action'] = 'Turning Point',
						['alt_type'] = 'BARO',
						['number'] = 8,
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = true,
						['ETA'] = 1955.9058944398,
						['y'] = -168885.89185564,
						['x'] = -321149.65459339,
						['name'] = 'Nav: 102/5NM',
						['ETA_locked'] = false,
						['speed'] = 215.83333333333,
						['formation_template'] = '',
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[5] = {
						['alt'] = 4572,
						['briefing_name'] = 'IP',
						['action'] = 'Turning Point',
						['alt_type'] = 'BARO',
						['number'] = 4,
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = false,
						['ETA'] = 1680.5885199224,
						['y'] = -140509.59300366,
						['x'] = -300949.52456093,
						['name'] = 'IP: 294/5NM',
						['ETA_locked'] = true,
						['speed'] = 215.83333333333,
						['formation_template'] = '',
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[10] = {
						['alt'] = 5486.4,
						['briefing_name'] = 'Split',
						['action'] = 'Turning Point',
						['alt_type'] = 'BARO',
						['number'] = 9,
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = true,
						['ETA'] = 2582.1947927201,
						['y'] = -48366.877791534,
						['x'] = -382363.89378212,
						['name'] = 'Split: 102/73NM',
						['ETA_locked'] = false,
						['speed'] = 215.83333333333,
						['formation_template'] = '',
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
									[1] = {
										['number'] = 1,
										['auto'] = false,
										['id'] = 'WrappedAction',
										['enabled'] = true,
										['params'] = {
											['action'] = {
												['id'] = 'Option',
												['params'] = {
													['variantIndex'] = 1,
													['value'] = 393217,
													['name'] = 5,
													['formationIndex'] = 6,
												},
											},
										},
									},
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[3] = {
						['alt'] = 5486.4,
						['briefing_name'] = 'Join',
						['action'] = 'Turning Point',
						['alt_type'] = 'BARO',
						['number'] = 2,
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = false,
						['ETA'] = 1114.9037837838,
						['y'] = -44687.532928144,
						['x'] = -376613.15775978,
						['name'] = 'Join: 294/19NM',
						['ETA_locked'] = true,
						['speed'] = 215.83333333333,
						['formation_template'] = '',
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
									[1] = {
										['number'] = 1,
										['auto'] = false,
										['id'] = 'WrappedAction',
										['enabled'] = true,
										['params'] = {
											['action'] = {
												['id'] = 'Option',
												['params'] = {
													['variantIndex'] = 1,
													['value'] = 458753,
													['name'] = 5,
													['formationIndex'] = 7,
												},
											},
										},
									},
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[6] = {
						['alt'] = 4572,
						['briefing_name'] = 'Attack',
						['action'] = 'Turning Point',
						['alt_type'] = 'BARO',
						['number'] = 5,
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed_locked'] = false,
						['ETA'] = 1740.5885199224,
						['y'] = -153576.92011947,
						['x'] = -290631.21742998,
						['name'] = 'Attack: 294/9NM',
						['ETA_locked'] = true,
						['speed'] = 215.83333333333,
						['formation_template'] = '',
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
									[1] = {
										['enabled'] = true,
										['auto'] = false,
										['id'] = 'AttackGroup',
										['number'] = 1,
										['params'] = {
											['expend'] = 'All',
											['weaponType'] = 2032,
											['groupId'] = 61,
										},
									},
								},
							},
						},
						['type'] = 'Turning Point',
					},
					[11] = {
						['speed_locked'] = true,
						['briefing_name'] = 'Land',
						['action'] = 'Landing',
						['alt_type'] = 'BARO',
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['speed'] = 215.83333333333,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
								},
							},
						},
						['type'] = 'Land',
						['ETA'] = 2741.872630558,
						['ETA_locked'] = false,
						['y'] = -17639.5,
						['x'] = -397971,
						['name'] = 'Land: 102/19NM',
						['airdromeId'] = 4,
						['alt'] = 5486.4,
						['number'] = 10,
						['formation_template'] = '',
					},
				},
			},
			['hidden'] = false,
			['units'] = {
				[1] = {
					['alt'] = 0,
					['hardpoint_racks'] = true,
					['alt_type'] = 'RADIO',
					['livery_id'] = 'VF-74 Adversary',
					['onboard_num'] = '097',
					['speed'] = 5.138,
					['AddPropAircraft'] = {
						['INSAlignmentStored'] = true,
					},
					['heading'] = 0,
					['Radio'] = {
						[1] = {
							['channels'] = {
								[1] = 290.65,
								[2] = 327,
								[4] = 273.55,
								[3] = 302.45,
							},
						},
					},
					['callsign'] = {
						['name'] = 'Enfield71',
					},
					['psi'] = 0,
					['y'] = -17639.5,
					['x'] = -397971,
					['name'] = 'Pack 5 - FA 1/2 - CAS 1-1',
					['payload'] = {
						['pylons'] = {
							[6] = {
								['CLSID'] = '{LAU-138 wtip - AIM-9M}',
								['num'] = 10,
							},
							[2] = {
								['CLSID'] = '{MAK79_MK82 4}',
								['num'] = 7,
							},
							[3] = {
								['CLSID'] = '{MAK79_MK82 3L}',
								['num'] = 5,
							},
							[1] = {
								['CLSID'] = '{MAK79_MK82 4}',
								['num'] = 4,
							},
							[4] = {
								['CLSID'] = '{MAK79_MK82 3R}',
								['num'] = 6,
							},
							[5] = {
								['CLSID'] = '{LAU-138 wtip - AIM-9M}',
								['num'] = 1,
							},
						},
						['fuel'] = 7348,
						['flare'] = 60,
						['ammo_type'] = 1,
						['chaff'] = 140,
						['gun'] = 100,
					},
					['parking_id'] = 'C7',
					['skill'] = 'Player',
					['unitId'] = 100211,
					['type'] = 'F-14B',
				},
				[2] = {
					['alt'] = 0,
					['hardpoint_racks'] = true,
					['alt_type'] = 'RADIO',
					['livery_id'] = 'VF-74 Adversary',
					['onboard_num'] = '026',
					['speed'] = 5.138,
					['AddPropAircraft'] = {
						['INSAlignmentStored'] = true,
					},
					['heading'] = 0,
					['callsign'] = {
						['name'] = 'Enfield72',
					},
					['psi'] = 0,
					['y'] = -17539.5,
					['x'] = -397871,
					['name'] = 'Pack 5 - FA 1/2 - CAS 1-2',
					['payload'] = {
						['pylons'] = {
							[6] = {
								['CLSID'] = '{LAU-138 wtip - AIM-9M}',
								['num'] = 10,
							},
							[2] = {
								['CLSID'] = '{MAK79_MK82 4}',
								['num'] = 7,
							},
							[3] = {
								['CLSID'] = '{MAK79_MK82 3L}',
								['num'] = 5,
							},
							[1] = {
								['CLSID'] = '{MAK79_MK82 4}',
								['num'] = 4,
							},
							[4] = {
								['CLSID'] = '{MAK79_MK82 3R}',
								['num'] = 6,
							},
							[5] = {
								['CLSID'] = '{LAU-138 wtip - AIM-9M}',
								['num'] = 1,
							},
						},
						['fuel'] = 7348,
						['flare'] = 60,
						['ammo_type'] = 1,
						['chaff'] = 140,
						['gun'] = 100,
					},
					['parking_id'] = 'C8',
					['skill'] = 'High',
					['unitId'] = 100212,
					['type'] = 'F-14B',
				},
				[4] = {
					['alt'] = 0,
					['hardpoint_racks'] = true,
					['alt_type'] = 'RADIO',
					['livery_id'] = 'VF-74 Adversary',
					['onboard_num'] = '039',
					['speed'] = 5.138,
					['AddPropAircraft'] = {
						['INSAlignmentStored'] = true,
					},
					['heading'] = 0,
					['callsign'] = {
						['name'] = 'Enfield74',
					},
					['psi'] = 0,
					['y'] = -17339.5,
					['x'] = -397671,
					['name'] = 'Pack 5 - FA 1/2 - CAS 1-4',
					['payload'] = {
						['pylons'] = {
							[6] = {
								['CLSID'] = '{LAU-138 wtip - AIM-9M}',
								['num'] = 10,
							},
							[2] = {
								['CLSID'] = '{MAK79_MK82 4}',
								['num'] = 7,
							},
							[3] = {
								['CLSID'] = '{MAK79_MK82 3L}',
								['num'] = 5,
							},
							[1] = {
								['CLSID'] = '{MAK79_MK82 4}',
								['num'] = 4,
							},
							[4] = {
								['CLSID'] = '{MAK79_MK82 3R}',
								['num'] = 6,
							},
							[5] = {
								['CLSID'] = '{LAU-138 wtip - AIM-9M}',
								['num'] = 1,
							},
						},
						['fuel'] = 7348,
						['flare'] = 60,
						['ammo_type'] = 1,
						['chaff'] = 140,
						['gun'] = 100,
					},
					['parking_id'] = 'C10',
					['skill'] = 'High',
					['unitId'] = 100214,
					['type'] = 'F-14B',
				},
				[3] = {
					['alt'] = 0,
					['hardpoint_racks'] = true,
					['alt_type'] = 'RADIO',
					['livery_id'] = 'VF-74 Adversary',
					['onboard_num'] = '016',
					['speed'] = 5.138,
					['AddPropAircraft'] = {
						['INSAlignmentStored'] = true,
					},
					['heading'] = 0,
					['callsign'] = {
						['name'] = 'Enfield73',
					},
					['psi'] = 0,
					['y'] = -17439.5,
					['x'] = -397771,
					['name'] = 'Pack 5 - FA 1/2 - CAS 1-3',
					['payload'] = {
						['pylons'] = {
							[6] = {
								['CLSID'] = '{LAU-138 wtip - AIM-9M}',
								['num'] = 10,
							},
							[2] = {
								['CLSID'] = '{MAK79_MK82 4}',
								['num'] = 7,
							},
							[3] = {
								['CLSID'] = '{MAK79_MK82 3L}',
								['num'] = 5,
							},
							[1] = {
								['CLSID'] = '{MAK79_MK82 4}',
								['num'] = 4,
							},
							[4] = {
								['CLSID'] = '{MAK79_MK82 3R}',
								['num'] = 6,
							},
							[5] = {
								['CLSID'] = '{LAU-138 wtip - AIM-9M}',
								['num'] = 1,
							},
						},
						['fuel'] = 7348,
						['flare'] = 60,
						['ammo_type'] = 1,
						['chaff'] = 140,
						['gun'] = 100,
					},
					['parking_id'] = 'C9',
					['skill'] = 'High',
					['unitId'] = 100213,
					['type'] = 'F-14B',
				},
			},
			['y'] = -17639.5,
			['radioSet'] = true,
			['name'] = 'Pack 5 - FA 1/2 - CAS 1',
			['communication'] = true,
			['x'] = -397971,
			['start_time'] = 1,
			['task'] = 'CAS',
			['frequency'] = 290.65,
		},
		['flight'] = 1,
		['role'] = 'main',
		['unitname'] = 'Pack 5 - FA 1/2 - CAS 1-1',
		['pack_n'] = 5,
		['tgt_wp'] = 7,
		['target'] = {
			['elements'] = {
				[1] = {
					['name'] = '103 Radar',
				},
				[2] = {
					['name'] = '103 Command Post',
				},
			},
			['groupId'] = 61,
			['class'] = 'vehicle',
			['name'] = '103 EWR Site',
			['y'] = -162609.85714285,
			['x'] = -283498.57142856,
			['attributes'] = {
				[1] = 'soft',
			},
			['dead_last'] = 0,
			['alive'] = 100,
			['priority'] = 3,
			['task'] = 'CAS',
			['firepower'] = {
				['min'] = 20,
				['max'] = 20,
			},
		},
	},
	['title'] = 'Desert F14 89',
	['day'] = 5,
	['coop'] = 1,
	['variation'] = 14,
	['mission_duration'] = 10800,
	['mission'] = 8,
}
