oob_air = {
	['blue'] = {
		[7] = {
			['type'] = 'C-130',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Anti-ship Strike'] = false,
				['Fighter Sweep'] = false,
				['CAS'] = false,
				['SEAD'] = false,
				['Ground Attack'] = false,
				['Intercept'] = false,
				['AWACS'] = false,
				['Refueling'] = false,
				['Escort'] = false,
				['Reconnaissance'] = false,
				['Pinpoint Strike'] = false,
				['Runway Attack'] = false,
				['CAP'] = false,
				['Transport'] = true,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 1,
			},
			['name'] = '40 TAS',
			['livery'] = 'US Air Force',
			['base'] = 'Nellis AFB',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[1] = {
			['type'] = 'F-14B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 11,
				['kills_ground'] = 5,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Anti-ship Strike'] = false,
				['Fighter Sweep'] = true,
				['CAS'] = true,
				['SEAD'] = false,
				['Ground Attack'] = true,
				['Intercept'] = true,
				['AWACS'] = false,
				['Refueling'] = false,
				['Escort'] = true,
				['Reconnaissance'] = false,
				['Pinpoint Strike'] = false,
				['Runway Attack'] = false,
				['CAP'] = false,
				['Transport'] = false,
			},
			['properties'] = {
				['INSAlignmentStored'] = true,
			},
			['skill'] = 'High',
			['player'] = true,
			['name'] = 'FA 1/2',
			['livery'] = {
				[1] = 'VF-74 Adversary',
			},
			['roster'] = {
				['lost'] = 5,
				['damaged'] = 0,
				['ready'] = 14,
			},
			['base'] = 'Nellis AFB',
			['score_last'] = {
				['kills_ground'] = 4,
				['damaged'] = 0,
				['lost'] = 4,
				['kills_ship'] = 0,
				['kills_air'] = 5,
				['ready'] = 4,
			},
		},
		[2] = {
			['type'] = 'F-14B',
			['name'] = 'FA 3/2',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 29,
			},
			['tasks'] = {
			},
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[4] = {
			['type'] = 'F-4E',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
			['name'] = '4 TFS',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 30,
			},
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[8] = {
			['type'] = 'C-130',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Anti-ship Strike'] = false,
				['Fighter Sweep'] = false,
				['CAS'] = false,
				['SEAD'] = false,
				['Ground Attack'] = false,
				['Intercept'] = false,
				['AWACS'] = false,
				['Refueling'] = false,
				['Escort'] = false,
				['Reconnaissance'] = false,
				['Pinpoint Strike'] = false,
				['Runway Attack'] = false,
				['CAP'] = false,
				['Transport'] = true,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 2,
			},
			['name'] = '41 TAS',
			['livery'] = 'US Air Force',
			['base'] = 'Laughlin',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[9] = {
			['type'] = 'A-10A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 3,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Fighter Sweep'] = false,
				['Escort'] = false,
				['CAS'] = true,
				['Runway Attack'] = false,
				['Ground Attack'] = true,
				['Intercept'] = false,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 18,
			},
			['name'] = '104th FS',
			['livery'] = {
				[1] = '104th FS Maryland ANG, Baltimore (MD)',
			},
			['base'] = 'Nellis AFB',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[5] = {
			['type'] = 'E-3A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Anti-ship Strike'] = false,
				['Fighter Sweep'] = false,
				['CAS'] = false,
				['SEAD'] = false,
				['Ground Attack'] = false,
				['Intercept'] = false,
				['AWACS'] = true,
				['Refueling'] = false,
				['Escort'] = false,
				['Reconnaissance'] = false,
				['Pinpoint Strike'] = false,
				['Runway Attack'] = false,
				['CAP'] = false,
				['Transport'] = false,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 2,
			},
			['name'] = '963 AWCS',
			['livery'] = 'usaf standard',
			['base'] = 'Nellis AFB',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[10] = {
			['type'] = 'A-10A',
			['name'] = '172nd FS',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 30,
			},
			['tasks'] = {
			},
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[3] = {
			['type'] = 'F-4E',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USAF Aggressors',
			['tasks'] = {
				['Anti-ship Strike'] = false,
				['Fighter Sweep'] = true,
				['CAS'] = true,
				['SEAD'] = true,
				['Ground Attack'] = true,
				['Intercept'] = true,
				['AWACS'] = false,
				['Refueling'] = false,
				['Escort'] = true,
				['Reconnaissance'] = true,
				['Pinpoint Strike'] = false,
				['Runway Attack'] = false,
				['CAP'] = true,
				['Transport'] = false,
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = '34 TFS',
			['livery'] = '',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 18,
			},
			['base'] = 'Nellis AFB',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[6] = {
			['type'] = 'S-3B Tanker',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Anti-ship Strike'] = false,
				['Fighter Sweep'] = false,
				['CAS'] = false,
				['SEAD'] = false,
				['Ground Attack'] = false,
				['Intercept'] = false,
				['AWACS'] = false,
				['Refueling'] = true,
				['Escort'] = false,
				['Reconnaissance'] = false,
				['Pinpoint Strike'] = false,
				['Runway Attack'] = false,
				['CAP'] = false,
				['Transport'] = false,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '171 ARW',
			['livery'] = '',
			['base'] = 'Nellis AFB',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
	},
	['red'] = {
		[1] = {
			['type'] = 'MiG-23MLD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 1,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Anti-ship Strike'] = false,
				['Fighter Sweep'] = true,
				['CAS'] = false,
				['SEAD'] = false,
				['Ground Attack'] = false,
				['Intercept'] = true,
				['AWACS'] = false,
				['Refueling'] = false,
				['Escort'] = false,
				['Reconnaissance'] = false,
				['Pinpoint Strike'] = false,
				['Runway Attack'] = false,
				['CAP'] = true,
				['Transport'] = false,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = '1./76.IAP',
			['livery'] = {
				[1] = 'af standard',
				[2] = 'af standard-1',
				[3] = 'af standard-2',
			},
			['base'] = 'Tonopah AFB',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 1,
				['ready'] = 0,
			},
		},
		[2] = {
			['type'] = 'MiG-23MLD',
			['name'] = '2./76.IAP',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['tasks'] = {
			},
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[4] = {
			['type'] = 'MiG-25PD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Anti-ship Strike'] = false,
				['Fighter Sweep'] = false,
				['CAS'] = false,
				['SEAD'] = false,
				['Ground Attack'] = false,
				['Intercept'] = true,
				['AWACS'] = false,
				['Refueling'] = false,
				['Escort'] = false,
				['Reconnaissance'] = false,
				['Pinpoint Strike'] = false,
				['Runway Attack'] = false,
				['CAP'] = false,
				['Transport'] = false,
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = '787.IAP',
			['livery'] = 'af standard',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 6,
			},
			['base'] = 'Tonopah AFB',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[8] = {
			['type'] = 'MiG-21Bis',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 1,
				['kills_ground'] = 0,
			},
			['country'] = 'Poland',
			['tasks'] = {
				['Anti-ship Strike'] = false,
				['Fighter Sweep'] = true,
				['CAS'] = true,
				['SEAD'] = false,
				['Ground Attack'] = false,
				['Intercept'] = true,
				['AWACS'] = false,
				['Refueling'] = false,
				['Escort'] = false,
				['Reconnaissance'] = false,
				['Pinpoint Strike'] = false,
				['Runway Attack'] = false,
				['CAP'] = true,
				['Transport'] = false,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 5,
				['damaged'] = 0,
				['ready'] = 10,
			},
			['name'] = '1./26.PLM',
			['livery'] = 'Poland - Metal',
			['base'] = 'Groom Lake AFB',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 1,
				['kills_ship'] = 0,
				['kills_air'] = 1,
				['ready'] = 1,
			},
		},
		[16] = {
			['type'] = 'Su-25T',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Anti-ship Strike'] = false,
				['Fighter Sweep'] = false,
				['CAS'] = true,
				['SEAD'] = false,
				['Ground Attack'] = true,
				['Intercept'] = false,
				['AWACS'] = false,
				['Refueling'] = false,
				['Escort'] = false,
				['Reconnaissance'] = false,
				['Pinpoint Strike'] = false,
				['Runway Attack'] = false,
				['CAP'] = false,
				['Transport'] = false,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = '461st',
			['livery'] = {
				[1] = 'af standard 1',
			},
			['base'] = 'Groom Lake AFB',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[17] = {
			['type'] = 'Su-25T',
			['name'] = '461st-reserves',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 16,
			},
			['tasks'] = {
			},
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[9] = {
			['type'] = 'MiG-21Bis',
			['name'] = '2./26.PLM',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 9,
			},
			['tasks'] = {
			},
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[5] = {
			['type'] = 'MiG-23MLD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 1,
				['kills_ground'] = 0,
			},
			['country'] = 'Germany',
			['tasks'] = {
				['Anti-ship Strike'] = false,
				['Fighter Sweep'] = true,
				['CAS'] = false,
				['SEAD'] = false,
				['Ground Attack'] = false,
				['Intercept'] = true,
				['AWACS'] = false,
				['Refueling'] = false,
				['Escort'] = false,
				['Reconnaissance'] = false,
				['Pinpoint Strike'] = false,
				['Runway Attack'] = false,
				['CAP'] = true,
				['Transport'] = false,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 3,
				['damaged'] = 0,
				['ready'] = 11,
			},
			['name'] = 'I./JG-8',
			['livery'] = '',
			['base'] = 'Creech AFB',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 2,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 2,
			},
		},
		[10] = {
			['type'] = 'MiG-23MLD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Czech Republic',
			['tasks'] = {
				['Anti-ship Strike'] = false,
				['Fighter Sweep'] = false,
				['CAS'] = false,
				['SEAD'] = false,
				['Ground Attack'] = false,
				['Intercept'] = true,
				['AWACS'] = false,
				['Refueling'] = false,
				['Escort'] = false,
				['Reconnaissance'] = false,
				['Pinpoint Strike'] = false,
				['Runway Attack'] = false,
				['CAP'] = true,
				['Transport'] = false,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 3,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '1./17.SLP',
			['livery'] = '',
			['base'] = 'Pahute Airstrip',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 2,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 2,
			},
		},
		[11] = {
			['type'] = 'MiG-23MLD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Czech Republic',
			['tasks'] = {
				['Anti-ship Strike'] = false,
				['Fighter Sweep'] = false,
				['CAS'] = false,
				['SEAD'] = false,
				['Ground Attack'] = false,
				['Intercept'] = true,
				['AWACS'] = false,
				['Refueling'] = false,
				['Escort'] = false,
				['Reconnaissance'] = false,
				['Pinpoint Strike'] = false,
				['Runway Attack'] = false,
				['CAP'] = false,
				['Transport'] = false,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 6,
			},
			['name'] = '2./17.SLP',
			['livery'] = '',
			['base'] = 'Lincoln',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[3] = {
			['type'] = 'MiG-29A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Anti-ship Strike'] = false,
				['Fighter Sweep'] = false,
				['CAS'] = false,
				['SEAD'] = false,
				['Ground Attack'] = false,
				['Intercept'] = true,
				['AWACS'] = false,
				['Refueling'] = false,
				['Escort'] = false,
				['Reconnaissance'] = false,
				['Pinpoint Strike'] = false,
				['Runway Attack'] = false,
				['CAP'] = true,
				['Transport'] = false,
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = '35.IAP',
			['livery'] = {
				[1] = '',
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['base'] = 'Tonopah AFB',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[6] = {
			['type'] = 'MiG-23MLD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Germany',
			['tasks'] = {
				['Anti-ship Strike'] = false,
				['Fighter Sweep'] = true,
				['CAS'] = false,
				['SEAD'] = false,
				['Ground Attack'] = false,
				['Intercept'] = true,
				['AWACS'] = false,
				['Refueling'] = false,
				['Escort'] = false,
				['Reconnaissance'] = false,
				['Pinpoint Strike'] = false,
				['Runway Attack'] = false,
				['CAP'] = true,
				['Transport'] = false,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 3,
			},
			['name'] = 'II./JG-8',
			['livery'] = '',
			['base'] = 'Beatty',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[12] = {
			['type'] = 'MiG-23MLD',
			['name'] = '3./17.SLP',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['tasks'] = {
			},
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[13] = {
			['type'] = 'An-26B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Anti-ship Strike'] = false,
				['Fighter Sweep'] = false,
				['CAS'] = false,
				['SEAD'] = false,
				['Ground Attack'] = false,
				['Intercept'] = false,
				['AWACS'] = false,
				['Refueling'] = false,
				['Escort'] = false,
				['Reconnaissance'] = false,
				['Pinpoint Strike'] = false,
				['Runway Attack'] = false,
				['CAP'] = false,
				['Transport'] = true,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 2,
			},
			['name'] = '1.OSAP',
			['livery'] = {
				[1] = 'Aeroflot',
				[2] = 'RF Air Force',
			},
			['base'] = 'Tonopah Airport',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[7] = {
			['type'] = 'MiG-23MLD',
			['name'] = 'III./JG-8',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 7,
			},
			['tasks'] = {
			},
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['base'] = 'Reserves',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[14] = {
			['type'] = 'An-26B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Anti-ship Strike'] = false,
				['Fighter Sweep'] = false,
				['CAS'] = false,
				['SEAD'] = false,
				['Ground Attack'] = false,
				['Intercept'] = false,
				['AWACS'] = false,
				['Refueling'] = false,
				['Escort'] = false,
				['Reconnaissance'] = false,
				['Pinpoint Strike'] = false,
				['Runway Attack'] = false,
				['CAP'] = false,
				['Transport'] = true,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 1,
			},
			['name'] = '2.OSAP',
			['livery'] = {
				[1] = 'Aeroflot',
				[2] = 'RF Air Force',
			},
			['base'] = 'Tonopah AFB',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[15] = {
			['type'] = 'An-26B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Anti-ship Strike'] = false,
				['Fighter Sweep'] = false,
				['CAS'] = false,
				['SEAD'] = false,
				['Ground Attack'] = false,
				['Intercept'] = false,
				['AWACS'] = false,
				['Refueling'] = false,
				['Escort'] = false,
				['Reconnaissance'] = false,
				['Pinpoint Strike'] = false,
				['Runway Attack'] = false,
				['CAP'] = false,
				['Transport'] = true,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 1,
			},
			['name'] = '3.OSAP',
			['livery'] = {
				[1] = 'Aeroflot',
				[2] = 'RF Air Force',
			},
			['base'] = 'Groom Lake AFB',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
	},
}
